[phases.setup]
nixPkgs = ['php83', 'php83Extensions.gd', 'php83Extensions.mbstring', 'php83Extensions.pdo', 'php83Extensions.pdo_mysql']

[phases.install]
cmds = ['composer install --optimize-autoloader --no-dev']